spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.134:3307/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.134:8848
#    alicloud:
#      access-key: LTAI5tD3WWg6Cuq7jfPLwvqX
#      secret-key: PuxCvATGYdpuKYWzlnkwBSCIwXD7xh
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug
